### ISSUE TITLE
Oneindige loop / geen rooster zichtbaar

### ISSUE THREAD

**Issue by DynaSpan** [SpaceK33z/Pluff#187]
Als ik Pluff open blijft de tekst in het menu de hele verspringen van Nederlands naar de Engelste 'tags'. Hierdoor wordt het rooster ook niet geladen.

Heb zelf Opera op Windows 10, maar werkt ook niet in andere browsers of andere laptops.

**Comment by Drawer** [comment]
Welk OS en browser en browserversie?

2015-09-14 13:56 GMT+02:00 Milan Drossaerts <notifications@github.com>:

**Comment by DynaSpan** [comment]
Opera 31.0.1889.174 op Windows 10 x64. Werkt op een andere laptop met Chrome en W10 ook niet.

**Comment by Drawer** [comment]
Ahja, hier ook.

Ik gok op een stukke api @svrooij ?

**Comment by SpaceK33z** [comment]
Ah, heb vandaag Pluff naar een nieuwe server verhuisd, daar is wat misgegaan denk ik. Ik ga er zsm naar kijken. Dank voor het melden :).

**Comment by SpaceK33z** [comment]
Het zou nu opgelost moeten zijn. Ik heb meteen de nieuwe versie van Pluff live gezet die een nieuwe API gebruikt :).

**Comment by DynaSpan** [comment]
Hij blijft nu niet meer hangen in een loop, krijg alleen het menu en een witte pagina na het accepteren van de permissions. Ligt niet aan de cache.

**Comment by SpaceK33z** [comment]
Zou je in de devtools kunnen kijken wat voor error je krijgt @DynaSpan? Het werkt nu wel bij mij.

**Comment by DynaSpan** [comment]
@SpaceK33z 
```
TypeError: Cannot read property 'replace' of undefined
    at Object.exports.default.data.setInfo (https://pluff.nl/static/bundle-4f6fe3a.js:59:30902)
    at new exports.default (https://pluff.nl/static/bundle-4f6fe3a.js:59:20988)
    at invoke (https://pluff.nl/static/bundle-4f6fe3a.js:52:1274)
    at Object.instantiate (https://pluff.nl/static/bundle-4f6fe3a.js:52:1436)
    at $get (https://pluff.nl/static/bundle-4f6fe3a.js:53:17398)
    at link (https://pluff.nl/static/bundle-4f6fe3a.js:30:6796)
    at invokeLinkFn (https://pluff.nl/static/bundle-4f6fe3a.js:53:9180)
    at nodeLinkFn (https://pluff.nl/static/bundle-4f6fe3a.js:52:26873)
    at compositeLinkFn (https://pluff.nl/static/bundle-4f6fe3a.js:52:17198)
    at $get.node (https://pluff.nl/static/bundle-4f6fe3a.js:52:15754) <ng-view id="top" class="ng-scope" data-ng-animate="1">
```

**Comment by SpaceK33z** [comment]
@DynaSpan, zou je het nog eens willen proberen (na een refresh)? Heb net een fix gepushed.

**Comment by DynaSpan** [comment]
@SpaceK33z Helaas nog steeds, andere error:

```
TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.default.data.getTimeTable (https://pluff.nl/static/bundle-e420e69.js:59:31924)
    at new exports.default (https://pluff.nl/static/bundle-e420e69.js:59:21068)
    at invoke (https://pluff.nl/static/bundle-e420e69.js:52:1274)
    at Object.instantiate (https://pluff.nl/static/bundle-e420e69.js:52:1436)
    at $get (https://pluff.nl/static/bundle-e420e69.js:53:17398)
    at link (https://pluff.nl/static/bundle-e420e69.js:30:6796)
    at invokeLinkFn (https://pluff.nl/static/bundle-e420e69.js:53:9180)
    at nodeLinkFn (https://pluff.nl/static/bundle-e420e69.js:52:26873)
    at compositeLinkFn (https://pluff.nl/static/bundle-e420e69.js:52:17198)
    at $get.node (https://pluff.nl/static/bundle-e420e69.js:52:15754) <ng-view id="top" class="ng-scope" data-ng-animate="1">
```

**Comment by SpaceK33z** [comment]
De roostermakers hebben mijn klas niet aan mij 'toegekend', waardoor ik helaas dit gedeelte niet goed heb kunnen testen. Kun je eens proberen om het rooster van een andere klas / docent te kijken. E.g.: https://pluff.nl/search/teacher/Onk

**Comment by DynaSpan** [comment]
@SpaceK33z  een andere gebruiker werkt inderdaad wel. Zou wel zo 1, 2, 3 niet weten wat er anders zou zijn aan mijn rooster.

**Comment by SpaceK33z** [comment]
@DynaSpan, zou je nog eens kunnen kijken? Het zou nu gefixt moeten zijn...

**Comment by DynaSpan** [comment]
@SpaceK33z Gefixt!
